# ATTENTION:
# This workflow is designed as an entrypoint for GitHub Action's
# "Require status checks to pass" feature.
# Renaming the workflow or any of its jobs will require corresponding
# changes to the branch protection rules.

name: Check

on:
  pull_request:
    paths:
      - .github/workflows/check.yml
  pull_request_target:

permissions: {}

jobs:
  no-channel-branches:
    if: |
      startsWith(github.base_ref, 'nixos-') ||
      startsWith(github.base_ref, 'nixpkgs-')
    runs-on: ubuntu-24.04-arm
    steps:
      - run: |
          cat <<EOF
          The nixos-* and nixpkgs-* branches are pushed to by the channel
          release script and should not be merged into directly.

          Please target the equivalent release-* branch or master instead.
          EOF
          exit 1
