name: "PR opened"

on:
  pull_request_target:
    types: [opened]

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  update:
    name: update description
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const footer = `
            ---

            Add a :+1: [reaction] to [pull requests you find important].

            [reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
            [pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc`

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: context.payload.pull_request.body + footer,
            })
